//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTracker) DeepCopyInto(out *PodTracker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTracker.
func (in *PodTracker) DeepCopy() *PodTracker {
	if in == nil {
		return nil
	}
	out := new(PodTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodTracker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTrackerList) DeepCopyInto(out *PodTrackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodTracker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTrackerList.
func (in *PodTrackerList) DeepCopy() *PodTrackerList {
	if in == nil {
		return nil
	}
	out := new(PodTrackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodTrackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTrackerSpec) DeepCopyInto(out *PodTrackerSpec) {
	*out = *in
	if in.NSToWatch != nil {
		in, out := &in.NSToWatch, &out.NSToWatch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.BackendWriterConfig.DeepCopyInto(&out.BackendWriterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTrackerSpec.
func (in *PodTrackerSpec) DeepCopy() *PodTrackerSpec {
	if in == nil {
		return nil
	}
	out := new(PodTrackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTrackerStatus) DeepCopyInto(out *PodTrackerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTrackerStatus.
func (in *PodTrackerStatus) DeepCopy() *PodTrackerStatus {
	if in == nil {
		return nil
	}
	out := new(PodTrackerStatus)
	in.DeepCopyInto(out)
	return out
}
