{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "podtracker.fullname" . }}
  labels: {{ include "podtracker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "podtracker.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "podtracker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
