{{- if .Values.webhooksEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.fullname" . }}
  labels: {{ include "webhook.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
  selector: {{ include "podtracker.selectorLabels" . | nindent 4 }}
{{- end -}}
