---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-aurora-gc-ca-v1-podtracker
  failurePolicy: Fail
  name: mpodtracker.kb.io
  rules:
  - apiGroups:
    - networking.aurora.gc.ca
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podtrackers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-aurora-gc-ca-v1-podtracker
  failurePolicy: Fail
  name: vpodtracker.kb.io
  rules:
  - apiGroups:
    - networking.aurora.gc.ca
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podtrackers
  sideEffects: None
