# permissions for end users to edit podtrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podtracker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podtracker
    app.kubernetes.io/part-of: podtracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-editor-role
rules:
- apiGroups:
  - networking.aurora.gc.ca
  resources:
  - podtrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.aurora.gc.ca
  resources:
  - podtrackers/status
  verbs:
  - get
