{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "podtracker.fullname" . }}-leader
  labels: {{ include "podtracker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "podtracker.fullname" . }}-leader
subjects:
- kind: ServiceAccount
  name: {{ include "podtracker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
