{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "podtracker.fullname" . }}
  labels: {{ include "podtracker.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - networking.aurora.gc.ca
  resources:
  - podtrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.aurora.gc.ca
  resources:
  - podtrackers/finalizers
  verbs:
  - update
- apiGroups:
  - networking.aurora.gc.ca
  resources:
  - podtrackers/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
