# Adds namespace to all resources.
namespace: podtracker-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: podtracker-

resources:
- ../crd
- ../rbac
- ../manager
- ../prometheus

patches:
- path: manager_auth_proxy_patch.yaml
- path: manager_config_patch.yaml
